import Insertbuttoncomponents from "@/components/Insertbuttoncomponents";
import { useState } from "react";
import Buttoncomponents from "@/components/Buttoncomponents";
import Dailyweightcomponents from "@/components/Dailyweightcomponents";
import "@/styles/Frame10544.css";
const Frame10544 = () => {
    const [search_button_state_7_660, setSearch_button_state_7_660] =
        useState("default");
    const [buttonstate_7_569, setButtonstate_7_569] = useState("default");
    const [buttonstate_7_572, setButtonstate_7_572] = useState("default");
    const [transitionConfig7_660, setTransitionConfig7_660] = useState({});
    const [transitionConfig7_569, setTransitionConfig7_569] = useState({});
    const [transitionConfig7_572, setTransitionConfig7_572] = useState({});
    const transitionConfig: any = {
        "7:572_7:566_md": { transition: { duration: 0, ease: [0, 0, 1, 1] } }
    };

    const mouseover_7_660 = () => {
        setSearch_button_state_7_660("checked");
    };

    const mousedown_7_569 = () => {
        setButtonstate_7_569("checked");
    };

    const mousedown_7_572 = () => {
        setButtonstate_7_572("checked");
    };

    return (
        <div className="scroll-container">
            <div id="10_544" className="stroke-wrapper-10_544">
                <div className="Pixso-frame-10_544">
                    <div className="frame-content-10_544">
                        <div id="10_542" className="Pixso-frame-10_542">
                            <div className="frame-content-10_542">
                                <div id="10_541" className="Pixso-frame-10_541">
                                    <div className="frame-content-10_541">
                                        <p
                                            id="7_664"
                                            className="Pixso-paragraph-7_664"
                                        >
                                            {"7"}
                                        </p>
                                    </div>
                                </div>
                                <div id="10_545" className="Pixso-frame-10_545">
                                    <div className="frame-content-10_545">
                                        <div
                                            id="9_683"
                                            className="Pixso-frame-9_683"
                                        >
                                            <div className="frame-content-9_683">
                                                <div
                                                    id="7_667"
                                                    className="Pixso-frame-7_667"
                                                >
                                                    <div className="frame-content-7_667">
                                                        <p
                                                            id="7_665"
                                                            className="Pixso-paragraph-7_665"
                                                        >
                                                            {"TODAY"}
                                                        </p>
                                                        <p
                                                            id="9_684"
                                                            className="Pixso-paragraph-9_684"
                                                        >
                                                            {":"}
                                                        </p>
                                                        <div
                                                            id="9_681"
                                                            className="Pixso-frame-9_681"
                                                        >
                                                            <p
                                                                id="7_666"
                                                                className="Pixso-paragraph-7_666"
                                                            >
                                                                {"2026-07-11"}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div
                                                    id="9_675"
                                                    className="Pixso-frame-9_675"
                                                >
                                                    <div className="frame-content-9_675">
                                                        <p
                                                            id="9_676"
                                                            className="Pixso-paragraph-9_676"
                                                        >
                                                            {"AVERAGE"}
                                                        </p>
                                                        <p
                                                            id="9_685"
                                                            className="Pixso-paragraph-9_685"
                                                        >
                                                            {":"}
                                                        </p>
                                                        <div
                                                            id="9_682"
                                                            className="Pixso-frame-9_682"
                                                        >
                                                            <div
                                                                id="9_677"
                                                                className="Pixso-frame-9_677"
                                                            >
                                                                <div className="frame-content-9_677">
                                                                    <p
                                                                        id="9_678"
                                                                        className="Pixso-paragraph-9_678"
                                                                    >
                                                                        {"30.5"}
                                                                    </p>
                                                                </div>
                                                            </div>
                                                            <p
                                                                id="9_679"
                                                                className="Pixso-paragraph-9_679"
                                                            >
                                                                {"kg"}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div
                                            id="7_663"
                                            className="Pixso-frame-7_663"
                                        >
                                            <div className="frame-content-7_663">
                                                <div
                                                    id="7_584"
                                                    className="stroke-wrapper-7_584"
                                                >
                                                    <div className="Pixso-frame-7_584">
                                                        <div className="shadow-blend-unknown-0"></div>
                                                        <div className="frame-content-7_584">
                                                            <p
                                                                id="7_585"
                                                                className="Pixso-paragraph-7_585"
                                                            >
                                                                {"WEI"}
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <div className="stroke-7_584"></div>
                                                </div>
                                                <Insertbuttoncomponents
                                                    id="7_660"
                                                    className="Pixso-instance-7_660"
                                                    search_button_state={
                                                        search_button_state_7_660
                                                    }
                                                    transitionConfig={
                                                        transitionConfig7_660
                                                    }
                                                    mouseover={mouseover_7_660}
                                                    slot_7_593={
                                                        <p
                                                            id="2_18"
                                                            className="Pixso-paragraph-2_18"
                                                        >
                                                            {"INSERT"}
                                                        </p>
                                                    }
                                                ></Insertbuttoncomponents>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="7_579" className="Pixso-frame-7_579">
                            <div className="frame-content-7_579">
                                <div
                                    id="4_549"
                                    className="Pixso-vector-4_549"
                                ></div>
                                <div id="7_577" className="Pixso-frame-7_577">
                                    <div className="frame-content-7_577">
                                        <Buttoncomponents
                                            id="7_569"
                                            className="Pixso-instance-7_569"
                                            buttonstate={buttonstate_7_569}
                                            transitionConfig={
                                                transitionConfig7_569
                                            }
                                            mousedown={mousedown_7_569}
                                            slot_7_554={
                                                <p
                                                    id="2_22"
                                                    className="Pixso-paragraph-2_22"
                                                >
                                                    {"<"}
                                                </p>
                                            }
                                        ></Buttoncomponents>
                                        <div
                                            id="7_576"
                                            className="Pixso-frame-7_576"
                                        >
                                            <div className="frame-content-7_576">
                                                <div
                                                    id="11_558"
                                                    className="Pixso-frame-11_558"
                                                >
                                                    <div className="frame-content-11_558">
                                                        <div
                                                            id="11_556"
                                                            className="Pixso-frame-11_556"
                                                        >
                                                            <div className="frame-content-11_556">
                                                                <p
                                                                    id="11_555"
                                                                    className="Pixso-paragraph-11_555"
                                                                >
                                                                    {"2026"}
                                                                </p>
                                                            </div>
                                                        </div>
                                                        <div
                                                            id="9_669"
                                                            className="Pixso-frame-9_669"
                                                        >
                                                            <div className="frame-content-9_669">
                                                                <p
                                                                    id="9_670"
                                                                    className="Pixso-paragraph-9_670"
                                                                >
                                                                    {"JUL"}
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div
                                                    id="3_1773"
                                                    className="Pixso-frame-3_1773"
                                                >
                                                    <div className="frame-content-3_1773">
                                                        <div
                                                            id="3_1698"
                                                            className="Pixso-frame-3_1698"
                                                        >
                                                            <div className="frame-content-3_1698">
                                                                <Dailyweightcomponents
                                                                    id="3_1699"
                                                                    className="Pixso-instance-3_1699"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1700"
                                                                    className="Pixso-instance-3_1700"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1701"
                                                                    className="Pixso-instance-3_1701"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1702"
                                                                    className="Pixso-instance-3_1702"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_31"
                                                                            className="Pixso-paragraph-2_31"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1703"
                                                                    className="Pixso-instance-3_1703"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_8"
                                                                            className="Pixso-paragraph-2_8"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1704"
                                                                    className="Pixso-instance-3_1704"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_6"
                                                                            className="Pixso-paragraph-2_6"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1705"
                                                                    className="Pixso-instance-3_1705"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_12"
                                                                            className="Pixso-paragraph-2_12"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                            </div>
                                                        </div>
                                                        <div
                                                            id="3_1713"
                                                            className="Pixso-frame-3_1713"
                                                        >
                                                            <div className="frame-content-3_1713">
                                                                <Dailyweightcomponents
                                                                    id="3_1714"
                                                                    className="Pixso-instance-3_1714"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_30"
                                                                            className="Pixso-paragraph-2_30"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1715"
                                                                    className="Pixso-instance-3_1715"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_25"
                                                                            className="Pixso-paragraph-2_25"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1716"
                                                                    className="Pixso-instance-3_1716"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_24"
                                                                            className="Pixso-paragraph-2_24"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1717"
                                                                    className="Pixso-instance-3_1717"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_15"
                                                                            className="Pixso-paragraph-2_15"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1718"
                                                                    className="Pixso-instance-3_1718"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_32"
                                                                            className="Pixso-paragraph-2_32"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1719"
                                                                    className="Pixso-instance-3_1719"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_11"
                                                                            className="Pixso-paragraph-2_11"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1720"
                                                                    className="Pixso-instance-3_1720"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_2"
                                                                            className="Pixso-paragraph-2_2"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                            </div>
                                                        </div>
                                                        <div
                                                            id="3_1697"
                                                            className="Pixso-frame-3_1697"
                                                        >
                                                            <div className="frame-content-3_1697">
                                                                <Dailyweightcomponents
                                                                    id="3_1676"
                                                                    className="Pixso-instance-3_1676"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_29"
                                                                            className="Pixso-paragraph-2_29"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1685"
                                                                    className="Pixso-instance-3_1685"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_34"
                                                                            className="Pixso-paragraph-2_34"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1687"
                                                                    className="Pixso-instance-3_1687"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_17"
                                                                            className="Pixso-paragraph-2_17"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1689"
                                                                    className="Pixso-instance-3_1689"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_28"
                                                                            className="Pixso-paragraph-2_28"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1691"
                                                                    className="Pixso-instance-3_1691"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_26"
                                                                            className="Pixso-paragraph-2_26"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1693"
                                                                    className="Pixso-instance-3_1693"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_10"
                                                                            className="Pixso-paragraph-2_10"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1695"
                                                                    className="Pixso-instance-3_1695"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_4"
                                                                            className="Pixso-paragraph-2_4"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                            </div>
                                                        </div>
                                                        <div
                                                            id="3_1728"
                                                            className="Pixso-frame-3_1728"
                                                        >
                                                            <div className="frame-content-3_1728">
                                                                <Dailyweightcomponents
                                                                    id="3_1729"
                                                                    className="Pixso-instance-3_1729"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_1"
                                                                            className="Pixso-paragraph-2_1"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1730"
                                                                    className="Pixso-instance-3_1730"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_23"
                                                                            className="Pixso-paragraph-2_23"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1731"
                                                                    className="Pixso-instance-3_1731"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_21"
                                                                            className="Pixso-paragraph-2_21"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1732"
                                                                    className="Pixso-instance-3_1732"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_27"
                                                                            className="Pixso-paragraph-2_27"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1733"
                                                                    className="Pixso-instance-3_1733"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_3"
                                                                            className="Pixso-paragraph-2_3"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1734"
                                                                    className="Pixso-instance-3_1734"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_13"
                                                                            className="Pixso-paragraph-2_13"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1735"
                                                                    className="Pixso-instance-3_1735"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_20"
                                                                            className="Pixso-paragraph-2_20"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                            </div>
                                                        </div>
                                                        <div
                                                            id="3_1743"
                                                            className="Pixso-frame-3_1743"
                                                        >
                                                            <div className="frame-content-3_1743">
                                                                <Dailyweightcomponents
                                                                    id="3_1744"
                                                                    className="Pixso-instance-3_1744"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_7"
                                                                            className="Pixso-paragraph-2_7"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1745"
                                                                    className="Pixso-instance-3_1745"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_9"
                                                                            className="Pixso-paragraph-2_9"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1746"
                                                                    className="Pixso-instance-3_1746"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_33"
                                                                            className="Pixso-paragraph-2_33"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1747"
                                                                    className="Pixso-instance-3_1747"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_14"
                                                                            className="Pixso-paragraph-2_14"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1748"
                                                                    className="Pixso-instance-3_1748"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_5"
                                                                            className="Pixso-paragraph-2_5"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1749"
                                                                    className="Pixso-instance-3_1749"
                                                                    weigjtinputstate="TRUE"
                                                                    slot_3_568={
                                                                        <p
                                                                            id="2_19"
                                                                            className="Pixso-paragraph-2_19"
                                                                        >
                                                                            {
                                                                                "42"
                                                                            }
                                                                        </p>
                                                                    }
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1750"
                                                                    className="Pixso-instance-3_1750"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                            </div>
                                                        </div>
                                                        <div
                                                            id="3_1758"
                                                            className="Pixso-frame-3_1758"
                                                        >
                                                            <div className="frame-content-3_1758">
                                                                <Dailyweightcomponents
                                                                    id="3_1759"
                                                                    className="Pixso-instance-3_1759"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1760"
                                                                    className="Pixso-instance-3_1760"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1761"
                                                                    className="Pixso-instance-3_1761"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1762"
                                                                    className="Pixso-instance-3_1762"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1763"
                                                                    className="Pixso-instance-3_1763"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1764"
                                                                    className="Pixso-instance-3_1764"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                                <Dailyweightcomponents
                                                                    id="3_1765"
                                                                    className="Pixso-instance-3_1765"
                                                                    weigjtinputstate="FALSE"
                                                                ></Dailyweightcomponents>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <Buttoncomponents
                                            id="7_572"
                                            className="Pixso-instance-7_572"
                                            buttonstate={buttonstate_7_572}
                                            transitionConfig={
                                                transitionConfig7_572
                                            }
                                            mousedown={mousedown_7_572}
                                            slot_7_554={
                                                <p
                                                    id="2_16"
                                                    className="Pixso-paragraph-2_16"
                                                >
                                                    {">"}
                                                </p>
                                            }
                                        ></Buttoncomponents>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="stroke-10_544"></div>
            </div>
        </div>
    );
};
export default Frame10544;
